# Generated by Django 4.1.7 on 2023-04-21 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_alter_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='stripe_price',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
